---
title: "DATA606 - Final Meetup"
author: Jason Bryer, Ph.D.
date: May 8, 2019
knit: (function(inputFile, encoding) { input.dir <- normalizePath(dirname(inputFile)); rmarkdown::render(input = inputFile, encoding = encoding, quiet=FALSE, output_file = paste0(input.dir,'/../docs/slides/', tools::file_path_sans_ext(basename(inputFile)), '.html')); })
output:
  ioslides_presentation:
    self_contained: true
    widescreen: true
    smaller: true
---
	
<div class="notes">
Documentation on using ioslides is available here:
http://rmarkdown.rstudio.com/ioslides_presentation_format.html
Some slides are adopted (or copied) from OpenIntro: https://www.openintro.org/
</div>

```{r setup, echo=FALSE, results='hide', warning=FALSE, message=FALSE}
set.seed(2112)
library(ggplot2)
library(openintro)
library(DATA606)
library(reshape2)
library(psych)
library(reshape2)
library(xtable)
options(width=100)
par(mar=c(2.5,1,2,1))

```

## Final Exam

* Will be available Monday.

* Due by end of day May 19th.

* You may use your book and course materials.

* There are two parts:
	1. Part one multiple choice questions and short answer questions.
	2. Part two has a small data set to analyze with R, then answer some interpretation questions.

* Put your answers in the Rmarkdown file and submit the PDF file. **Please do not post your answers online!**

## Presentations

* Fernando Figueres (7.23) http://rpubs.com/ffigueres/d606-hwpres
* Mohamed Zaman (7.39) http://rpubs.com/thasleem/d606_presentation
* Michael O'Donnell (8.3)
* Habib Hkan (8.7) https://www.youtube.com/watch?v=Y3pgXd7lwkI&feature=youtu.be https://api.rpubs.com/habibkhan89/494285
* Weijian Cai (7.35) https://youtu.be/wuxMA2jU6n8 http://rpubs.com/weicai/494213  


## My Work

My research interest is in propensity score methods. Propensity score analysis (PSA) is a quasi-experimental design used to estimate causality from observational studies. It is generally conducted in two phases:

1. Estimate propensity scores (i.e. probability of being in the treatment) using the observed covariates.
	a. Check balance
	b. Re-estimate propensity scores
2. Estimate effect sizes using typical group differences (e.g. t-tests)

Areas I have worked on:

* Multilevel PSA (see [`multilevelPSA`](http://jason.bryer.org/multilevelPSA) R package)
* Matching with non-binary treatments (see [`TriMatch`](http://jason.bryer.org/TriMatch) R package)
* Bootstrapping PSA (see [`PSAboot`](http://jason.bryer.org/PSAboot) R package)

## Thank You

This has been a great semester. Please don't hesitate to reach out:

* Email: jason.bryer@gmail.com
* Github: http://github.com/jbryer
* Personal Website: http://bryer.org
* [LinkedIn](https://www.linkedin.com/profile/view?id=AAMAAATGdnoBOWXg80yqna6fSkgnZdabZP7Ck9w&trk=hp-identity-name)
* Twitter: [jbryer](https://twitter.com/jbryer)

<br/><br/><br/>

Over the summer, the course website will be moved to [spring2019.data606.net](https://spring2019.data606.net).

You can download all course materials on [Github](https://github.com/jbryer/DATA606Spring2019). Click the [clone or download](https://github.com/jbryer/DATA606Spring2019/archive/master.zip) link to download a zip file.
