---
title: "Welcome to DATA606!"
author: "Jason Bryer"
date: 2019-01-15
categories: ["R"]
tags: ["Annoucement"]
---

Welcome to DATA606! My name is Dr. Jason Bryer and I will be your instructor for this semester. In addition to teaching this course, I am an Executive Director at Excelsior College where I am currently working on a Department of Education grant to develop a Diagnostic Assessment and Achievement of College Skills (see www.DAACS.net for more information). Couple of important notes as you get started:

* The course syllabus is on Github here: https://data606.net I will post all course materials there. Blackboard will be used primarily for submitting assignments.
* [Join the Slack channel by clicking here](https://join.slack.com/t/data606spring2019/shared_invite/enQtNTIzODEzODM4MzIwLWRkZmJiNTQzYmVmZGNhZDZjODAwNzExNmY5MWQ4ZTkzOWY0N2Q0ZTM5MTEzOWQwMDQxYjAzMTBkYjA2M2MzMzE). This will be our primary mode of communication. For private communications, you can email me at jason.bryer@gmail.com.
* Introduce yourself in the Getting Acquainted forum on Blackboard.
* Once you go through the syllabus, try starting Lab 0 as soon as you can. This will require you to install R and RStudio and will help get you get acquainted with R.
* The best way to reach me is by email at jason.bryer@gmail.com. If you would prefer to talk on the phone or setup a GoToMeeting session, it is best to suggest some times by email first.
* Our meetups will be on Wednesdays from 8pm to 9pm.
* I am looking forward to getting to know everyone and a fantastic semester! Good luck!


<!-- iframe src="/slides/2019-01-24-Intro_to_Course.html#1" width="1024px" height="768px"  frameborder="0" allowfullscreen>
</iframe -->
